import Products from '@/components/Home/Products';
import React from 'react';
export const metadata = {
  title: "All products - KidsStationary",
  description: "Generated by create next app",
};
const ProductsPage = () => {




    
    return (
        <div>
            <Products></Products>
        </div>
    );
};

export default ProductsPage;